<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <DebugType>full</DebugType>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DebugType>none</DebugType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="HK.Net.Core" Version="1.0.1" />
        <PackageReference Include="HK.Net.Runtime.Win64" Version="1.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.18"/>
        <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
        <PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.0-preview" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="alarmTraceImage\" />
      <Folder Include="Handlers\" />
      <Folder Include="Logs\" />
    </ItemGroup>

    <ItemGroup>
      <Content Remove="Resources\SuperBrainModelInfo.json" />
      <None Include="Resources\SuperBrainModelInfo.json">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </None>
      <Content Remove="Resources\SuperBrainModelResponse.json" />
      <None Include="Resources\SuperBrainModelResponse.json">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </None>
      <None Update="HCNetSDKCom\AnalyzeData.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="HCNetSDKCom\AudioIntercom.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="HCNetSDKCom\AudioRender.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="HCNetSDKCom\HCAlarm.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="HCNetSDKCom\HCAlarm.lib">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="HCNetSDKCom\HCCoreDevCfg.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="HCNetSDKCom\HCDisplay.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="HCNetSDKCom\HCGeneralCfgMgr.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="HCNetSDKCom\HCGeneralCfgMgr.lib">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="HCNetSDKCom\HCIndustry.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="HCNetSDKCom\HCPlayBack.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="HCNetSDKCom\HCPreview.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="HCNetSDKCom\HCPreview.lib">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="HCNetSDKCom\HCVoiceTalk.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="HCNetSDKCom\libiconv2.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="HCNetSDKCom\OpenAL32.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="HCNetSDKCom\StreamTransClient.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="HCNetSDKCom\SystemTransform.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Remove="Logs\log-20251028.txt" />
    </ItemGroup>

</Project>
